name = "salon-citrine-team"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SESSION"
id = "15711a0ae59f411693baf6e64bd304dd"

[images]
binding = "IMAGES"
