insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-4300-4000-8000-0000000200000001', 'Haircuts', 'NEW CLIENT HAIRCUT', 'First time at Salon Citrine? Welcome! This is the service for you, as it gives your stylist more time to consult & familiarize themselves with your hair. Shampoo & blowout included.', 5500, 60, true, false, false, 1);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-4300-4000-8000-0000000300000001', 'Haircuts', 'HAIRCUT', 'For returning clients only! Your classic haircut to maintain your current shape. Shampoo & blowout included.
*Not for new shapes requiring more than 4+ inches off*', 5500, 60, true, false, false, 2);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-4300-4000-8000-0000000400000001', 'Haircuts', 'TRANSFORMATIVE HAIRCUT', 'Intended for big changes such as taking more than 3" off and creating new shape. *GREAT for a  new Shag / Mullet / Bob or Pixie*', 6500, 60, true, false, false, 3);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-4300-4000-8000-0000000500000001', 'Haircuts', 'CLIPPER CUT', 'Maintaining your personalized tapered look, typically with clippers, but not limited to.
Shampoo & style included.', 4500, 60, true, false, false, 4);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-4300-4000-8000-0000000600000001', 'Haircuts', 'DRY CUT', 'Maintenance haircut with no shampoo, style, or product.  Come in with clean, dry hair down.', 6000, 60, true, false, false, 5);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-4300-4000-8000-0000000700000001', 'Haircuts', 'FRINGE / UNDERCUT MAINTENANCE', 'This is the ideal freshen up between haircuts. *Good for Bang trims, undercut trims, & neckline cleanups*', 3000, 30, true, false, false, 6);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-4300-4000-8000-0000000800000001', 'Haircuts', 'BABY''S FIRST HAIRCUT', 'Is it time to get rid of the baby mullet, or simply get it out of their eyes? We''re here for you. For 0-2 year olds.', 2000, 60, true, false, false, 7);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-4300-4000-8000-0000000900000001', 'Haircuts', 'LITTLE KID''S HAIRCUT', '2-5 year olds. *No shampoo experience included.', 3500, 60, true, false, false, 8);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-4300-4000-8000-0000000a00000001', 'Haircuts', 'BIG KID''S HAIRCUT', '6-11 year olds, shampoo experience included if they want!', 4500, 60, true, false, false, 9);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-4300-4000-8000-0000000b00000001', 'Haircuts', 'DETANGLE', 'Need some help getting through mats or stubborn tangles, we got you!', 6500, 60, true, false, false, 10);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-de00-4000-8000-0000000c00000001', 'Color- Dimensional Color', 'FULL DIMENSIONAL COLOR & BLOWOUT', 'Full head of dimensional color. Plus a blowout! 

*Good for highlights/lowlights/balayage*', 15000, 120, true, false, false, 11);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-de00-4000-8000-0000000d00000001', 'Color- Dimensional Color', 'FULL DIMENSIONAL COLOR & CUT', 'Full head of dimensional color. Plus a custom haircut! 

*Good for highlights/lowlights/balayage*', 20000, 120, true, false, false, 12);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-de00-4000-8000-0000000e00000001', 'Color- Dimensional Color', 'PARTIAL DIMENSIONAL COLOR & BLOWOUT', 'Intended to freshen up existing dimensional hair. Plus a blowout.

*Good for highlights/balayage*', 9000, 120, true, false, false, 13);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-de00-4000-8000-0000000f00000001', 'Color- Dimensional Color', 'PARTIAL DIMENSIONAL COLOR & CUT', 'Intended to freshen up existing dimensional hair.  Plus a custom haircut. 

*Good for highlights/balayage*', 14000, 120, true, false, false, 14);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-de00-4000-8000-0000001000000001', 'Color- Dimensional Color', 'MINI LIGHTS & BLOWOUT', 'Intended to brighten around the face or along the part. Plus a blowout.
*Good for face framing highlights/money piece, or color blocking*', 8000, 120, true, false, false, 15);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-de00-4000-8000-0000001100000001', 'Color- Dimensional Color', 'MINI LIGHTS & CUT', 'Intended to brighten around the face or along the part. Plus a custom Haircut.
*Good for face framing highlights/ "Money piece"*', 13000, 120, true, false, false, 16);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-8700-4000-8000-0000001200000001', 'Color- Bleach & Tone', 'ALL OVER BLEACH AND TONE & BLOWOUT', 'Solid blonde look, achieved by lightening from scalp to ends and toning to desired tone. Plus a blowout!', 30000, 120, true, false, false, 17);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-8700-4000-8000-0000001300000001', 'Color- Bleach & Tone', 'ALL OVER BLEACH AND TONE & HAIRCUT', 'Solid blonde look, achieved by lightening from scalp to ends and toning to desired tone. Plus a custom haircut!', 37500, 120, true, false, false, 18);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-8700-4000-8000-0000001400000001', 'Color- Bleach & Tone', 'BLEACH ROOT TOUCH UP & BLOWOUT', 'Intended to touch up the roots from previous bleach and toned hair. Plus a blowout!

*ONLY for roots 1" or under. If longer, book an All Over Bleach & Tone*', 15000, 120, true, false, false, 19);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-8700-4000-8000-0000001500000001', 'Color- Bleach & Tone', 'BLEACH ROOT TOUCH UP & HAIRCUT', 'Intended to touch up the roots from previous bleach and toned hair. Plus a custom haircut!  

*ONLY for roots 1" or under. If longer, book an All Over Bleach & Tone*', 22500, 120, true, false, false, 20);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-5200-4000-8000-0000001600000001', 'Color- Single Color & Root Touch Ups', 'ALL OVER COLOR WITH BLOWOUT', 'One solid color from scalp to ends, typically darker. *NOT for dimensional color or going lighter* Plus a blowout!', 10000, 120, true, false, false, 21);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-5200-4000-8000-0000001700000001', 'Color- Single Color & Root Touch Ups', 'ALL OVER COLOR WITH HAIRCUT', 'One solid color from scalp to ends, typically darker. *NOT for dimensional color or going lighter* Plus a custom haircut!', 15000, 120, true, false, false, 22);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-5200-4000-8000-0000001800000001', 'Color- Single Color & Root Touch Ups', 'ROOT TOUCH UP WITH A BLOWOUT', 'One solid color intended to touch up all over color. Plus a blowout! 

*NOT for highlights or dimensional lightening*', 8000, 120, true, false, false, 23);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-5200-4000-8000-0000001900000001', 'Color- Single Color & Root Touch Ups', 'ROOT TOUCH UP WITH A HAIRCUT', 'One solid color intended to touch up all over color. Plus a Haircut!

*NOT for highlights or dimensional lightening*', 13000, 120, true, false, false, 24);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-5200-4000-8000-0000001a00000001', 'Color- Single Color & Root Touch Ups', 'GLOSS WITH A BLOWOUT', 'Semi permanent color, intended to slightly tint natural color or refresh the tone of previously lightened hair. Plus a blowout.', 8000, 120, true, false, false, 25);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-5200-4000-8000-0000001b00000001', 'Color- Single Color & Root Touch Ups', 'GLOSS WITH A HAIRCUT', 'Semi permanent color, intended to slightly tint natural color or refresh the tone of previously lightened hair. Plus a custom haircut!', 10500, 120, true, false, false, 26);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-8a00-4000-8000-0000001c00000001', 'Color- Vivids / Fashion Colors', 'COLOR CONSULTATION', 'Not sure what service to schedule for? Curious if your hair goals are achievable? This is for you!

*MUST BE SCHEDULED BEFORE BIG COLOR TRANSFORMATIONS*
*Fee goes towards final service if scheduled at consultation*', 2000, 15, false, false, false, 27);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-8a00-4000-8000-0000001d00000001', 'Color- Vivids / Fashion Colors', 'VIVID TRANSFORMATION', '!! THIS SERVICE REQUIRES A COLOR CONSULTATION BEFORE SCHEDULING !!
** Consults over text accepted as well as in person **
*! Final price equals out to $100/hour.
Intended for full transformation with vivids. Two step process where hair is lifted and then vivid color is applied.', 25000, 120, true, false, true, 28);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-cb00-4000-8000-0000001e00000001', 'Hair Treatments', 'ADD-ON: HOT TOWEL TREATMENT', '*NOT A STANDALONE SERVICE.*
Add a hot towel & aromatherapy to your shampoo experience.', 500, 30, false, true, false, 29);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-cb00-4000-8000-0000001f00000001', 'Hair Treatments', 'ADD-ON: DEEP CONDITION', '*NOT A STANDALONE SERVICE.*
Does your hair need some extra moisture or strengthening? Book this for a custom deep condition and pampering moment!', 2000, 30, true, true, false, 30);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-cb00-4000-8000-0000002000000001', 'Hair Treatments', 'ADD-ON: MALIBU TREATMENT', 'Amazing treatments for pre-color, mineral & buildup removal, post swim or vacation, and more. 
*NOT A STANDALONE SERVICE.*', 3000, 30, true, true, false, 31);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-cb00-4000-8000-0000002100000001', 'Hair Treatments', 'ADD-ON:SCALP REVITALIZING TREATMENT', 'Feel rejuvenated with this scalp & hair treatment!
Fully unwind with a warm, weighted eye mask & cozy aromas. 
»Start off with a stimulating dry brushing. Remove buildup with a double cleanse & scalp scrub. Relax & re-energize with a Jade  comb & thorough massage. Finish with a balancing & hydrating deep condition with a hot towel!
*Ear plugs available for ultimate relaxation*

*NOT A STANDALONE SERVICE.*', 4000, 30, true, true, false, 32);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-cb00-4000-8000-0000002200000001', 'Hair Treatments', 'ADD-ON: K-18 TREATMENT', 'Repair and protect. This can be done with a color service or as a stand alone treatment.
*Must schedule blowout if scheduling a stand alone treatment*', 4000, 30, true, true, false, 33);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-cb00-4000-8000-0000002300000001', 'Hair Treatments', 'ADD-ON: STYLING EDUCATION', 'Some extra 1 on 1 styling education for you!
*NOT A STANDALONE SERVICE.*', 1000, 30, true, true, false, 34);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-cb00-4000-8000-0000002400000001', 'Hair Treatments', 'HAIR TINSEL', 'Make your hair sparkle! 
We have a variety of colors and application methods available- *If you''re wanting a specific color or application method, please leave a note or contact us before appt*
*Price includes 1 application, additional applications are $5 each', 1000, 60, true, false, false, 35);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-cb00-4000-8000-0000002500000001', 'Hair Treatments', 'BLOWOUT', 'Start with a relaxing shampoo and scalp massage and leave with a beautiful style!', 5000, 60, true, false, false, 36);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-cb00-4000-8000-0000002600000001', 'Hair Treatments', 'SILK PRESS', 'Scalp cleanse, deep condition, blow dry & flat iron.', 10000, 60, true, false, false, 37);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-cb00-4000-8000-0000002700000001', 'Hair Treatments', 'KERATIN COMPLEX TREATMENT', 'Transform and revitalize your hair with our Keratin Complex Treatment. This professional service nourishes, and smooths your hair, leaving it sleek, shiny, and frizz-free for weeks. Not sure if this is the service for you? Schedule a complimentary consultation!', 30000, 60, true, false, false, 38);
insert into public.services (id, category, name, description, base_price_cents, duration_minutes, price_varies, is_addon, requires_consultation, sort_order) values ('b2000001-1a00-4000-8000-0000002800000001', 'Hair Consultations', 'CONSULTATION FOR KERATIN COMPLEX', 'Curious about getting a keratin treatment? Book this to learn more and see how we can help you!', null, 15, false, false, false, 39);